#!/usr/bin/env python3
"""
autograph moc — generate Maps of Content from vault cards.
All domain/type/status logic from schema.json. No hardcoded values.

Commands:
  moc.py generate <vault-dir> [schema.json]
  moc.py generate <vault-dir> [schema.json] --domain <name>
"""

import sys
import json
from pathlib import Path
from collections import defaultdict
from datetime import datetime

from common import (
    load_schema, parse_frontmatter, walk_vault, rel_path,
    infer_domain, get_node_types, get_status_order
)


def build_moc_data(vault_dir: Path, schema: dict, domain_filter: str = None) -> dict:
    """Scan vault, group cards by domain → type → industry/category → status."""
    files = walk_vault(vault_dir)
    domains = defaultdict(list)

    for md in files:
        rp = rel_path(md, vault_dir)
        try:
            content = md.read_text(errors='replace')
        except Exception:
            continue

        fm, body, _ = parse_frontmatter(content)
        if fm is None:
            continue

        domain = fm.get('domain') or infer_domain(rp, schema)
        if domain_filter and domain != domain_filter:
            continue

        card_type = fm.get('type', 'note')
        status = fm.get('status', '')
        name = fm.get('title') or md.stem.replace('-', ' ').title()
        rp_noext = rp.replace('.md', '')

        card = {
            'path': rp_noext,
            'name': name,
            'type': card_type,
            'status': status,
            'priority': fm.get('priority', ''),
            'industry': fm.get('industry', 'Other'),
            'region': fm.get('region', ''),
            'deal_status': fm.get('deal_status', ''),
            'deal_deadline': fm.get('deal_deadline', ''),
            'responsible': fm.get('responsible', ''),
            'potential': fm.get('potential', ''),
            'source': fm.get('source', ''),
            'description': fm.get('description', ''),
        }
        domains[domain].append(card)

    return dict(domains)


def format_card_line(card: dict) -> str:
    """Format a single MOC line with context."""
    path = card['path']
    name = card['name']
    parts = []

    if card['status']:
        parts.append(card['status'])
    if card['priority']:
        parts.append(f"p:{card['priority']}")
    if card['deal_status']:
        parts.append(card['deal_status'])
    if card['deal_deadline']:
        parts.append(f"⏰ {card['deal_deadline']}")
    if card['region']:
        parts.append(card['region'].upper())
    if card['responsible']:
        parts.append(f"→ {card['responsible']}")
    if card['potential']:
        parts.append(f"🔥{card['potential']}")

    context = ', '.join(parts)
    return f"- [[{path}|{name}]]{' — ' + context if context else ''}"


def generate_moc(domain: str, cards: list, schema: dict) -> str:
    """Generate MOC markdown for a domain."""
    status_order = get_status_order(schema)
    lines = [
        f"---",
        f'description: "MOC — {domain.title()} domain index ({len(cards)} cards)"',
        f"type: moc",
        f"---",
        f"",
        f"# MOC — {domain.title()}",
        f"",
        f"_Auto-generated by autograph. {datetime.now().strftime('%Y-%m-%d %H:%M')}_",
        f"_Cards: {len(cards)}_",
        f"",
    ]

    # Group by type
    by_type = defaultdict(list)
    for c in cards:
        by_type[c['type']].append(c)

    for card_type in sorted(by_type.keys()):
        type_cards = by_type[card_type]
        lines.append(f"## {card_type.title()} ({len(type_cards)})")
        lines.append("")

        # Sub-group by industry
        by_industry = defaultdict(list)
        for c in type_cards:
            by_industry[c['industry']].append(c)

        for industry in sorted(by_industry.keys()):
            ind_cards = by_industry[industry]
            if len(by_industry) > 1:
                lines.append(f"### {industry}")
                lines.append("")

            # Sort by status priority
            ind_cards.sort(key=lambda c: status_order.get(c['status'], 99))

            for c in ind_cards:
                lines.append(format_card_line(c))

            lines.append("")

    # Stats
    type_counts = defaultdict(int)
    status_counts = defaultdict(int)
    for c in cards:
        type_counts[c['type']] += 1
        if c['status']:
            status_counts[c['status']] += 1

    lines.append("## Stats")
    lines.append("")
    lines.append("| Type | Count |")
    lines.append("|------|-------|")
    for t, count in sorted(type_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| {t} | {count} |")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    for s, count in sorted(status_counts.items(), key=lambda x: -x[1]):
        lines.append(f"| {s} | {count} |")

    return '\n'.join(lines)


def main():
    args = sys.argv[1:]
    if not args or args[0] in ('-h', '--help'):
        print(__doc__)
        sys.exit(0)

    cmd = args[0]
    vault_dir = Path(args[1]) if len(args) > 1 else None

    if not vault_dir or not vault_dir.is_dir():
        print("Error: vault directory required", file=sys.stderr)
        sys.exit(1)

    schema_path = None
    for a in args:
        if a.endswith('.json') and Path(a).exists():
            schema_path = Path(a)
            break
    schema = load_schema(schema_path)

    domain_filter = None
    if '--domain' in args:
        idx = args.index('--domain')
        if idx + 1 < len(args):
            domain_filter = args[idx + 1]

    if cmd == 'generate':
        data = build_moc_data(vault_dir, schema, domain_filter)

        moc_dir = vault_dir / 'MOC'
        moc_dir.mkdir(exist_ok=True)
        total_links = 0

        if domain_filter:
            cards = data.get(domain_filter, [])
            moc_text = generate_moc(domain_filter, cards, schema)
            outpath = moc_dir / f'MOC-{domain_filter}.md'
            outpath.write_text(moc_text)
            link_count = moc_text.count('[[')
            total_links += link_count
            print(f"✓ Generated: {outpath.relative_to(vault_dir)}")
            print(f"  {link_count} wikilinks")
        else:
            for domain, cards in sorted(data.items()):
                if not cards:
                    continue
                moc_text = generate_moc(domain, cards, schema)
                outpath = moc_dir / f'MOC-{domain}.md'
                outpath.write_text(moc_text)
                link_count = moc_text.count('[[')
                total_links += link_count
                print(f"✓ Generated: {outpath.relative_to(vault_dir)}")
                print(f"  {link_count} wikilinks")

        print(f"\nTotal: {total_links} wikilinks across {len(data)} domains")
    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
